# Generated by Django 3.1.4 on 2021-01-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='book_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
